"""changelogin to Activity Types

Revision ID: 34cb295cab75
Revises: 826de3741ede
Create Date: 2026-02-28 09:49:11.522620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34cb295cab75'
down_revision: Union[str, Sequence[str], None] = '826de3741ede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###\
    op.execute("ALTER TYPE activity_type_enum RENAME VALUE 'authentication' TO 'AUTH'")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
