"""add autoincrements

Revision ID: 434ccfc8d331
Revises: 4f68dd95b88e
Create Date: 2026-02-28 12:12:52.414185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '434ccfc8d331'
down_revision: Union[str, Sequence[str], None] = '4f68dd95b88e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='status_enum'), nullable=False))
    op.add_column('users', sa.Column('contact_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'contact_number')
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
