"""add ReadOnly

Revision ID: 436d6895fa6b
Revises: 41ce460cce8c
Create Date: 2026-02-28 10:06:47.379164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '436d6895fa6b'
down_revision: Union[str, Sequence[str], None] = '41ce460cce8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE user_type_enum ADD VALUE 'READONLY'")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
