"""adding id for pages

Revision ID: 53771148bee7
Revises: 7a749b8a8241
Create Date: 2026-02-28 11:52:47.140094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53771148bee7'
down_revision: Union[str, Sequence[str], None] = '7a749b8a8241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('page_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_pages_page_id'), 'pages', ['page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pages_page_id'), table_name='pages')
    op.drop_column('pages', 'page_id')
    # ### end Alembic commands ###
