"""institution id to trainee

Revision ID: 68ab6ae99687
Revises: 8a79606a96c6
Create Date: 2026-02-28 12:18:51.727291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68ab6ae99687'
down_revision: Union[str, Sequence[str], None] = '8a79606a96c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainees', sa.Column('institution_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'trainees', 'institutions', ['institution_id'], ['institution_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trainees', type_='foreignkey')
    op.drop_column('trainees', 'institution_id')
    # ### end Alembic commands ###
