"""adding new user type program approver

Revision ID: 7505963c7716
Revises: 81694e2c5c9b
Create Date: 2026-02-28 12:37:19.924328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7505963c7716'
down_revision: Union[str, Sequence[str], None] = '81694e2c5c9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE user_type_enum ADD VALUE 'PROGRAM_APPROVER';")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
