"""removing instution id on trainee

Revision ID: 779430b0abf7
Revises: d2bca0df3c0e
Create Date: 2026-02-28 12:49:14.317369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '779430b0abf7'
down_revision: Union[str, Sequence[str], None] = 'd2bca0df3c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('trainees_institution_id_fkey'), 'trainees', type_='foreignkey')
    op.drop_column('trainees', 'institution_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainees', sa.Column('institution_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('trainees_institution_id_fkey'), 'trainees', 'institutions', ['institution_id'], ['institution_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
