"""adding the rest

Revision ID: 7a749b8a8241
Revises: 436d6895fa6b
Create Date: 2026-02-28 10:38:15.297474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a749b8a8241'
down_revision: Union[str, Sequence[str], None] = '436d6895fa6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('institution_name', sa.String(), nullable=False),
    sa.Column('institution_abbr', sa.String(), nullable=True),
    sa.Column('institution_type', sa.Enum('ACADEMIC', 'INDUSTRY', 'GOVERNMENT', 'SELF', name='institution_type_enum'), nullable=False),
    sa.Column('institution_domain', sa.String(), nullable=True),
    sa.Column('institution_image', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('institution_id'),
    sa.UniqueConstraint('institution_abbr'),
    sa.UniqueConstraint('institution_name')
    )
    op.create_index(op.f('ix_institutions_institution_id'), 'institutions', ['institution_id'], unique=False)
    op.create_table('institution_to_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'INACTIVE', name='status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.institution_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institution_to_user_id'), 'institution_to_user', ['id'], unique=False)
    op.create_table('programs',
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('program_name', sa.String(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('program_image', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.institution_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('program_id'),
    sa.UniqueConstraint('program_name')
    )
    op.create_index(op.f('ix_programs_program_id'), 'programs', ['program_id'], unique=False)
    op.create_table('program_approvers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='status_enum'), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.program_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_approvers_id'), 'program_approvers', ['id'], unique=False)
    op.create_table('program_user_institution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'INACTIVE', name='status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.institution_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.program_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_user_institution_id'), 'program_user_institution', ['id'], unique=False)
    op.create_table('timesheets',
    sa.Column('timesheet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hours_worked', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='status_enum'), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.institution_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.program_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('timesheet_id')
    )
    op.create_index(op.f('ix_timesheets_timesheet_id'), 'timesheets', ['timesheet_id'], unique=False)
    op.add_column('users', sa.Column('is_approved', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('user_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_image')
    op.drop_column('users', 'is_approved')
    op.drop_index(op.f('ix_timesheets_timesheet_id'), table_name='timesheets')
    op.drop_table('timesheets')
    op.drop_index(op.f('ix_program_user_institution_id'), table_name='program_user_institution')
    op.drop_table('program_user_institution')
    op.drop_index(op.f('ix_program_approvers_id'), table_name='program_approvers')
    op.drop_table('program_approvers')
    op.drop_index(op.f('ix_programs_program_id'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_institution_to_user_id'), table_name='institution_to_user')
    op.drop_table('institution_to_user')
    op.drop_index(op.f('ix_institutions_institution_id'), table_name='institutions')
    op.drop_table('institutions')
    # ### end Alembic commands ###
