"""add login to Activity Types

Revision ID: 826de3741ede
Revises: e2bc951c6274
Create Date: 2026-02-28 09:46:56.791174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '826de3741ede'
down_revision: Union[str, Sequence[str], None] = 'e2bc951c6274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE activity_type ADD VALUE 'authentication'")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
