"""add trainee and contract

Revision ID: 8a79606a96c6
Revises: 434ccfc8d331
Create Date: 2026-02-28 12:13:45.820493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a79606a96c6'
down_revision: Union[str, Sequence[str], None] = '434ccfc8d331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainees',
    sa.Column('trainee_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trainee_id')
    )
    op.create_index(op.f('ix_trainees_trainee_id'), 'trainees', ['trainee_id'], unique=False)
    op.create_table('contracts',
    sa.Column('contract_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('trainee_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ON_LEAVE', name='contract_status_enum'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.institution_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.program_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.trainee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contract_id')
    )
    op.create_index(op.f('ix_contracts_contract_id'), 'contracts', ['contract_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contracts_contract_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_trainees_trainee_id'), table_name='trainees')
    op.drop_table('trainees')
    # ### end Alembic commands ###
