"""initial schema

Revision ID: e2bc951c6274
Revises: 
Create Date: 2026-02-28 09:40:07.000418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2bc951c6274'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages',
    sa.Column('page_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('page_name')
    )
    op.create_index(op.f('ix_pages_page_name'), 'pages', ['page_name'], unique=False)
    op.create_table('activities',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.Enum('DELETE', 'READ', 'CREATE', 'UPDATE', name='activity_type_enum'), nullable=False),
    sa.Column('activity_page', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_page'], ['pages.page_name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_index(op.f('ix_activities_activity_id'), 'activities', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activities_user_id'), 'activities', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_user_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_activity_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_pages_page_name'), table_name='pages')
    op.drop_table('pages')
    # ### end Alembic commands ###
