"""fixing id for page

Revision ID: e9108436472d
Revises: 53771148bee7
Create Date: 2026-02-28 11:55:11.045792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9108436472d'
down_revision: Union[str, Sequence[str], None] = '53771148bee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # convert existing string ids to integer values, casting explicitly
    op.alter_column(
        'pages',
        'page_id',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using='page_id::integer',
        autoincrement=True,
    )
    op.drop_index(op.f('ix_pages_page_name'), table_name='pages')
    op.create_index(op.f('ix_pages_page_name'), 'pages', ['page_name'], unique=True)
    # ensure autoincrement behaviour by creating a sequence and setting default
    op.execute(
        "CREATE SEQUENCE IF NOT EXISTS pages_page_id_seq;"
    )
    op.execute(
        "ALTER TABLE pages ALTER COLUMN page_id SET DEFAULT nextval('pages_page_id_seq');"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pages_page_name'), table_name='pages')
    op.create_index(op.f('ix_pages_page_name'), 'pages', ['page_name'], unique=False)
    # remove default sequence so it matches varchar column
    op.execute("ALTER TABLE pages ALTER COLUMN page_id DROP DEFAULT;")
    # when downgrading, cast integer back to text
    op.alter_column(
        'pages',
        'page_id',
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        postgresql_using='page_id::varchar',
        autoincrement=True,
    )
    # ### end Alembic commands ###
